"""add_sector_watch_and_document_tables

Revision ID: e054cbada3f2
Revises: b2c3d4e5f6a7
Create Date: 2026-04-12 21:15:54.145264

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e054cbada3f2'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ns_documents',
    sa.Column('doc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doc_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('viking_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('section_count', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('structure_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index(op.f('ix_ns_documents_created_at'), 'ns_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_ns_documents_created_by'), 'ns_documents', ['created_by'], unique=False)
    op.create_index(op.f('ix_ns_documents_doc_type'), 'ns_documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_ns_documents_status'), 'ns_documents', ['status'], unique=False)
    op.create_index(op.f('ix_ns_documents_viking_uri'), 'ns_documents', ['viking_uri'], unique=False)
    op.create_table('ns_process_definitions',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doc_types', sa.JSON(), nullable=False),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('definition_md', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('viking_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('ns_process_executions',
    sa.Column('execution_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('process_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doc_ids', sa.JSON(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('completed_steps', sa.Integer(), nullable=False),
    sa.Column('flagged_steps', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('findings_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index(op.f('ix_ns_process_executions_process_name'), 'ns_process_executions', ['process_name'], unique=False)
    op.create_index(op.f('ix_ns_process_executions_session_id'), 'ns_process_executions', ['session_id'], unique=False)
    op.create_index(op.f('ix_ns_process_executions_status'), 'ns_process_executions', ['status'], unique=False)
    op.create_table('sector_watch',
    sa.Column('industry_sectors', sa.JSON(), nullable=False),
    sa.Column('state_codes', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sector_watch_owner_id'), 'sector_watch', ['owner_id'], unique=False)
    op.drop_index(op.f('ix_ns_al_event_type'), table_name='ns_audit_log')
    op.drop_index(op.f('ix_ns_al_filing_id'), table_name='ns_audit_log')
    op.drop_index(op.f('ix_ns_al_severity'), table_name='ns_audit_log')
    op.drop_index(op.f('ix_ns_al_timestamp'), table_name='ns_audit_log')
    op.create_index(op.f('ix_ns_audit_log_event_type'), 'ns_audit_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_ns_audit_log_filing_id'), 'ns_audit_log', ['filing_id'], unique=False)
    op.create_index(op.f('ix_ns_audit_log_severity'), 'ns_audit_log', ['severity'], unique=False)
    op.create_index(op.f('ix_ns_audit_log_timestamp'), 'ns_audit_log', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_ns_bh_topic_domain'), table_name='ns_belief_history')
    op.create_index(op.f('ix_ns_belief_history_domain'), 'ns_belief_history', ['domain'], unique=False)
    op.create_index(op.f('ix_ns_belief_history_topic'), 'ns_belief_history', ['topic'], unique=False)
    op.drop_index(op.f('ix_ns_bs_domain'), table_name='ns_belief_states')
    op.create_index(op.f('ix_ns_belief_states_domain'), 'ns_belief_states', ['domain'], unique=False)
    op.alter_column('ns_citations', 'source_url',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.drop_index(op.f('ix_ns_dt_filing_id'), table_name='ns_decision_traces')
    op.drop_index(op.f('ix_ns_dt_started_at'), table_name='ns_decision_traces')
    op.create_index(op.f('ix_ns_decision_traces_filing_id'), 'ns_decision_traces', ['filing_id'], unique=False)
    op.create_index(op.f('ix_ns_decision_traces_started_at'), 'ns_decision_traces', ['started_at'], unique=False)
    op.alter_column('ns_entity_relations', 'context',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_index(op.f('ix_ns_er_source'), table_name='ns_entity_relations')
    op.drop_index(op.f('ix_ns_er_target'), table_name='ns_entity_relations')
    op.create_index(op.f('ix_ns_entity_relations_source'), 'ns_entity_relations', ['source'], unique=False)
    op.create_index(op.f('ix_ns_entity_relations_target'), 'ns_entity_relations', ['target'], unique=False)
    op.drop_index(op.f('ix_ns_er_provider_tag'), table_name='ns_eval_runs')
    op.drop_index(op.f('ix_ns_er_run_at'), table_name='ns_eval_runs')
    op.create_index(op.f('ix_ns_eval_runs_provider_tag'), 'ns_eval_runs', ['provider_tag'], unique=False)
    op.create_index(op.f('ix_ns_eval_runs_run_at'), 'ns_eval_runs', ['run_at'], unique=False)
    op.alter_column('ns_feedback_log', 'old_value',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('ns_feedback_log', 'new_value',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('ns_feedback_log', 'reason',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_index(op.f('ix_ns_fl_filing_id'), table_name='ns_feedback_log')
    op.create_index(op.f('ix_ns_feedback_log_filing_id'), 'ns_feedback_log', ['filing_id'], unique=False)
    op.alter_column('ns_memories', 'embedding_text',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.drop_index(op.f('ix_ns_memories_ns'), table_name='ns_memories')
    op.drop_index(op.f('ix_ns_memories_type'), table_name='ns_memories')
    op.create_index(op.f('ix_ns_memories_memory_type'), 'ns_memories', ['memory_type'], unique=False)
    op.create_index(op.f('ix_ns_memories_namespace'), 'ns_memories', ['namespace'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ns_memories_namespace'), table_name='ns_memories')
    op.drop_index(op.f('ix_ns_memories_memory_type'), table_name='ns_memories')
    op.create_index(op.f('ix_ns_memories_type'), 'ns_memories', ['memory_type'], unique=False)
    op.create_index(op.f('ix_ns_memories_ns'), 'ns_memories', ['namespace'], unique=False)
    op.alter_column('ns_memories', 'embedding_text',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.drop_index(op.f('ix_ns_feedback_log_filing_id'), table_name='ns_feedback_log')
    op.create_index(op.f('ix_ns_fl_filing_id'), 'ns_feedback_log', ['filing_id'], unique=False)
    op.alter_column('ns_feedback_log', 'reason',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ns_feedback_log', 'new_value',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ns_feedback_log', 'old_value',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_ns_eval_runs_run_at'), table_name='ns_eval_runs')
    op.drop_index(op.f('ix_ns_eval_runs_provider_tag'), table_name='ns_eval_runs')
    op.create_index(op.f('ix_ns_er_run_at'), 'ns_eval_runs', ['run_at'], unique=False)
    op.create_index(op.f('ix_ns_er_provider_tag'), 'ns_eval_runs', ['provider_tag'], unique=False)
    op.drop_index(op.f('ix_ns_entity_relations_target'), table_name='ns_entity_relations')
    op.drop_index(op.f('ix_ns_entity_relations_source'), table_name='ns_entity_relations')
    op.create_index(op.f('ix_ns_er_target'), 'ns_entity_relations', ['target'], unique=False)
    op.create_index(op.f('ix_ns_er_source'), 'ns_entity_relations', ['source'], unique=False)
    op.alter_column('ns_entity_relations', 'context',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_ns_decision_traces_started_at'), table_name='ns_decision_traces')
    op.drop_index(op.f('ix_ns_decision_traces_filing_id'), table_name='ns_decision_traces')
    op.create_index(op.f('ix_ns_dt_started_at'), 'ns_decision_traces', ['started_at'], unique=False)
    op.create_index(op.f('ix_ns_dt_filing_id'), 'ns_decision_traces', ['filing_id'], unique=False)
    op.alter_column('ns_citations', 'source_url',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.drop_index(op.f('ix_ns_belief_states_domain'), table_name='ns_belief_states')
    op.create_index(op.f('ix_ns_bs_domain'), 'ns_belief_states', ['domain'], unique=False)
    op.drop_index(op.f('ix_ns_belief_history_topic'), table_name='ns_belief_history')
    op.drop_index(op.f('ix_ns_belief_history_domain'), table_name='ns_belief_history')
    op.create_index(op.f('ix_ns_bh_topic_domain'), 'ns_belief_history', ['topic', 'domain'], unique=False)
    op.drop_index(op.f('ix_ns_audit_log_timestamp'), table_name='ns_audit_log')
    op.drop_index(op.f('ix_ns_audit_log_severity'), table_name='ns_audit_log')
    op.drop_index(op.f('ix_ns_audit_log_filing_id'), table_name='ns_audit_log')
    op.drop_index(op.f('ix_ns_audit_log_event_type'), table_name='ns_audit_log')
    op.create_index(op.f('ix_ns_al_timestamp'), 'ns_audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_ns_al_severity'), 'ns_audit_log', ['severity'], unique=False)
    op.create_index(op.f('ix_ns_al_filing_id'), 'ns_audit_log', ['filing_id'], unique=False)
    op.create_index(op.f('ix_ns_al_event_type'), 'ns_audit_log', ['event_type'], unique=False)
    op.drop_index(op.f('ix_sector_watch_owner_id'), table_name='sector_watch')
    op.drop_table('sector_watch')
    op.drop_index(op.f('ix_ns_process_executions_status'), table_name='ns_process_executions')
    op.drop_index(op.f('ix_ns_process_executions_session_id'), table_name='ns_process_executions')
    op.drop_index(op.f('ix_ns_process_executions_process_name'), table_name='ns_process_executions')
    op.drop_table('ns_process_executions')
    op.drop_table('ns_process_definitions')
    op.drop_index(op.f('ix_ns_documents_viking_uri'), table_name='ns_documents')
    op.drop_index(op.f('ix_ns_documents_status'), table_name='ns_documents')
    op.drop_index(op.f('ix_ns_documents_doc_type'), table_name='ns_documents')
    op.drop_index(op.f('ix_ns_documents_created_by'), table_name='ns_documents')
    op.drop_index(op.f('ix_ns_documents_created_at'), table_name='ns_documents')
    op.drop_table('ns_documents')
    # ### end Alembic commands ###
